# Generated by Django 6.0.7 on 2026-07-18 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(db_index=True, max_length=64, verbose_name='ID новости (GNews)')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(max_length=1000, verbose_name='Ссылка на источник')),
                ('image', models.URLField(blank=True, max_length=1000, verbose_name='Изображение')),
                ('source_name', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('category', models.CharField(blank=True, max_length=32, verbose_name='Категория')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(db_index=True, max_length=64, verbose_name='ID новости (GNews)')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(max_length=1000, verbose_name='Ссылка на источник')),
                ('image', models.URLField(blank=True, max_length=1000, verbose_name='Изображение')),
                ('source_name', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('category', models.CharField(blank=True, max_length=32, verbose_name='Категория')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_articles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранная новость',
                'verbose_name_plural': 'Избранные новости',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'article_id'), name='unique_user_article')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_categories', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранная категория',
                'verbose_name_plural': 'Избранные категории',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'category'), name='unique_user_category')],
            },
        ),
    ]
